version: '3.1'

services:
    sqlserver2019:
        image: wachira90/sqlserver:2019-CU5-ubuntu-16.04
        container_name: sqlserver2019
        environment:
            - "ACCEPT_EULA=Y"
#            - "MSSQL_AGENT_ENABLED=True"
            - "SA_PASSWORD=passwordexample"
            - "SQLSERVER_DATABASE=testdb"
            - "MSSQL_PID=Enterprise"
            - "SQLSERVER_USER=wachira90"
            - "SQLSERVER_PASSWORD=passwordexample"
        volumes:
            - ./data/:/var/opt/mssql/data/:rw
        ports:
            - 1433:1433
        networks:
            sqlserver2019_lan:    

networks:
    sqlserver2019_lan:
